export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"

export const PRODUCT_FAILURE="PRODUCT_FAILURE"

export const SEARCH_FILTER="SEARCH_FILTER"

export const CHECK_FILTER="CHECK_FILTER"

export const ITEM_COUNT="ITEM_COUNT"